create_clock -name {clk_master} -period 83.33333333 [get_ports clk_master]
create_generated_clock -name {clk_100MHz} -source [get_ports clk_master] -divide_by 8 -multiply_by 67 [get_nets clk_100MHz]
create_generated_clock -name {clk_50MHz} -source [get_nets clk_100MHz] -divide_by 2 [get_nets {clocks_generator0_counter[0]}]
create_generated_clock -name {clk_25MHz} -source [get_nets clk_100MHz] -divide_by 4 [get_nets {clocks_generator0_counter[1]}]
create_generated_clock -name {clk_20MHz} -source [get_nets clk_100MHz] -divide_by 5 [get_nets clk_core]
create_generated_clock -name {clk_12_5MHz} -source [get_nets clk_100MHz] -divide_by 8 [get_nets {clocks_generator0_counter[2]}]
